spring.application.name=api-gateway
server.port=8765

eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

spring.cloud.gateway.server.webmvc.routes[0].id=question-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/question/**

spring.cloud.gateway.server.webmvc.routes[1].id=quiz-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/quizz/**

spring.cloud.refresh.enabled=false