spring.application.name=quiz-service
server.port=8090

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://quiz-db:3306/quiz_db
spring.datasource.username=root
spring.datasource.password=Krishna2580.,@

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.validation=TRACE
logging.level.org.hibernate.validator=TRACE

spring.cloud.refresh.enabled=false