FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y libstdc++6 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY target/quiz-service .

RUN chmod +x quiz-service

EXPOSE 8090

ENTRYPOINT ["./quiz-service"]