FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y libstdc++6 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY target/question-service .

RUN chmod +x question-service

EXPOSE 8080

ENTRYPOINT ["./question-service","--spring.config.location=file:/config/application.properties"]