name: Build Question Service Windows Native Image

on:
  workflow_dispatch:

  push:
    branches:
      - graalvm-native
    paths:
      - "question-service/**"
      - ".github/workflows/windows-native-question-service.yml"

jobs:
  native-build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: question-service
        shell: pwsh

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: "21"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: true
          cache: maven

      - name: Verify Environment
        run: |
          java -version
          native-image --version
          .\mvnw.cmd -version

      - name: Build Native Image
        run: |
          .\mvnw.cmd `
            -Pnative `
            -DskipTests `
            native:compile

      - name: Upload Native Executable
        uses: actions/upload-artifact@v4
        with:
          name: question-service-native-windows
          path: question-service/target/*.exe