name: Build Quiz Service Native

on:
  workflow_dispatch:

  push:
    branches:
      - native-microservices
    paths:
      - "quiz-service/**"
      - ".github/workflows/quiz-service-native.yml"

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: quiz-service

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: "25"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: maven

      - name: Verify Environment
        run: |
          java -version
          native-image --version

      - name: Build Native Executable
        run: |
          chmod +x mvnw
          ./mvnw clean -Pnative -DskipTests native:compile

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./quiz-service
          file: ./quiz-service/Dockerfile.native
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/quiz-service-native:latest
            ghcr.io/${{ github.repository_owner }}/quiz-service-native:${{ github.sha }}